type Query {
  obtenerUsuarioPorEmail(email: String!): Usuario
  solicitudesPorFecha: [Solicitud!]!
  solicitudesPorAsignatura: [Solicitud!]!
  stockInsumosDisponibles: [Insumo!]!
  listarAsignaturas: [Asignatura]!
  listarInsumos: [Insumo]
  listarLaboratorios: [Laboratorio]
}

type Mutation {
  confirmarSolicitud(idSolicitud: ID!): Solicitud!
  crearUsuario(usuarioDto: UsuarioDto): Usuario  #FUNCIONA
  modificarSolicitud(idSolicitud: ID!, input: SolicitudInput!): Solicitud!
  eliminarSolicitud(idSolicitud: ID!): Boolean!
  crearSolicitud(input: CrearSolicitudInput!): Solicitud!
  forgotPassword(email: String): Boolean
  updatePasswordByCode(code: String, password: String): Boolean
  crearInsumo(input: InsumoInput!): Insumo
  modificarInsumo(id: ID!, input: InsumoInput!): Insumo
  eliminarInsumo(id: ID!): Boolean
  crearLaboratorio(nombre: String!, codigo: String!): Laboratorio
  crearAsignatura(nombre: String!, codigo: String!): Asignatura

}

type Solicitud {
  id: ID!
  fechaSolicitud: String
  fechaUso: String
  horario: String
  cantGrupos: Int
  estadoTarea: Boolean
  estadoAlerta: String
  usuario: Usuario
  asignatura: Asignatura
  laboratorio: Laboratorio
  insumos: [SolicitudInsumo!]
}


type Asignatura {
  id: ID!
  nombre: String!
  codigo: String!
}

type Laboratorio {
  id: ID!
  nombre: String!
  codigo: String!
}


type SolicitudInsumo {
  id: ID!
  insumo: Insumo!
  cantidad: Float!
}

input SolicitudInput {
  fechaUso: String
  horario: String
  cantGrupos: Int
  estadoAlerta: String
}

input CrearSolicitudInput {
  idUsuario: ID!
  idAsignatura: ID!
  idLaboratorio: ID!
  fechaUso: String!
  horario: String!
  cantGrupos: Int!
  insumos: [InsumoCantidadInput!]!
}

input InsumoCantidadInput {
  idInsumo: ID!
  cantidad: Float!
}
input UsuarioDto {
  id: Int
  nombre: String
  apellido: String
  email: String
  password:String
  accountLocked: Boolean
  enabled: Boolean
  roles: [Int]
}

type Role {
  id: Int
  name: String
  usuarios:[Usuario]
}
type Usuario {
  id: Int
  nombre: String
  apellido: String
  email: String
  password: String
  telephone: String
  accountLocked: Boolean
  enabled: Boolean
  roles: [Role]
}

type Insumo {
  id: ID!
  nombre: String
  tipo: String
  unidadMedida: String
  cantidad: Int
  stockDisponible: Int
}

input InsumoInput {
  nombre: String!
  tipo: String!
  unidadMedida: String!
  stockDisponible: Int!
}
