spring.application.name=proyecto
spring.datasource.url=jdbc:postgresql://localhost:5432/sistemaBdd
spring.datasource.username=postgres
spring.datasource.password=kamila
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.graphql.graphiql.enabled=true

application.mailing.frontend.activation-url: http://localhost:4200/activate-account
