--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2025-04-27 21:56:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 27600)
-- Name: asignatura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asignatura (
    id bigint NOT NULL,
    codigo character varying(255),
    nombre character varying(255),
    code character varying(255),
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.asignatura OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 27599)
-- Name: asignatura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asignatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 27608)
-- Name: insumo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.insumo (
    id bigint NOT NULL,
    cantidad integer,
    nombre character varying(255),
    stock_disponible integer,
    tipo character varying(255),
    unidad_medida character varying(255),
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone
);


ALTER TABLE public.insumo OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 27607)
-- Name: insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.insumo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 27616)
-- Name: laboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorio (
    id bigint NOT NULL,
    nombre character varying(255),
    codigo character varying(255),
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone
);


ALTER TABLE public.laboratorio OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 27615)
-- Name: laboratorio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 27622)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 27621)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 27628)
-- Name: solicitud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitud (
    id bigint NOT NULL,
    cant_grupos integer,
    estado boolean,
    fecha_solicitud date,
    fecha_uso date,
    horario character varying(255),
    id_asignatura bigint,
    id_laboratorio bigint,
    id_usuario bigint NOT NULL,
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    asignatura_id bigint,
    laboratorio_id bigint,
    usuario_id bigint
);


ALTER TABLE public.solicitud OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 27627)
-- Name: solicitud_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 27634)
-- Name: solicitud_insumo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitud_insumo (
    id bigint NOT NULL,
    cantidad double precision,
    id_insumo bigint,
    id_solicitud bigint,
    created_at timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    insumo_id bigint,
    solicitud_id bigint
);


ALTER TABLE public.solicitud_insumo OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 27633)
-- Name: solicitud_insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitud_insumo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitud_insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 27640)
-- Name: token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    status integer DEFAULT 1 NOT NULL,
    token character varying(255),
    validated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    type character varying(255),
    CONSTRAINT token_type_check CHECK (((type)::text = ANY ((ARRAY['VALIDATION'::character varying, 'RESET_PASSWORD'::character varying, 'REFRESH'::character varying])::text[])))
);


ALTER TABLE public.token OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 27639)
-- Name: token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 27647)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    account_locked boolean NOT NULL,
    apellido character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    last_modified_date timestamp(6) without time zone NOT NULL,
    nombre character varying(255),
    password character varying(255),
    reset_password_token character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 27646)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 27654)
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_roles (
    users_id bigint NOT NULL,
    roles_id bigint NOT NULL
);


ALTER TABLE public.usuario_roles OWNER TO postgres;

--
-- TOC entry 4906 (class 0 OID 27600)
-- Dependencies: 216
-- Data for Name: asignatura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asignatura (id, codigo, nombre, code, created_at, last_modified_date, name) FROM stdin;
1	QUI-001	Química General	\N	\N	\N	\N
2	QUI-002	Química Orgánica	\N	\N	\N	\N
3	IQI-003	Química Analítica	\N	\N	\N	\N
4	QUI-003	Bioquímica	\N	\N	\N	\N
5	IQI-007	Laboratorio Química Industrial	\N	\N	\N	\N
6	IQI-011	Mecánica De Fluidos	\N	\N	\N	\N
7	IQI-012	Microbiología	\N	\N	\N	\N
8	IQI-014	Transferencia De Calor Y Masa	\N	\N	\N	\N
9	IQI-017	Procesos Industriales	\N	\N	\N	\N
10	INF1234	Programación Avanzada	\N	\N	\N	\N
11	ELECT-01	Electromagnetísmo	\N	\N	\N	\N
\.


--
-- TOC entry 4908 (class 0 OID 27608)
-- Dependencies: 218
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.insumo (id, cantidad, nombre, stock_disponible, tipo, unidad_medida, created_at, last_modified_date) FROM stdin;
2	\N	Agua raz	18	Liquido	Litro	\N	\N
3	\N	Matraz	28	Envase	Unidad	\N	\N
4	\N	Tuvo de ensayo	80	Envase	Unidad	\N	\N
5	\N	Agua destilada	80	Liquido	Litro	\N	\N
6	\N	Cloruro de Sodio	30	Solido	Kilo	\N	\N
7	\N	Gotero Glucosa	40	Envase	Unidad	\N	\N
8	\N	Gafas de seguridad	100	Herramienta	Unidad	\N	\N
\.


--
-- TOC entry 4910 (class 0 OID 27616)
-- Dependencies: 220
-- Data for Name: laboratorio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.laboratorio (id, nombre, codigo, created_at, last_modified_date) FROM stdin;
4	Lab Química 1	LAB-Q01	\N	\N
5	Lab Química 2	LAB-Q02	\N	\N
6	Lab Ingeniería 1	LAB-I01	\N	\N
7	Lab Escuela Ingeniería	LAB-ICCI	\N	\N
8	Arquitectura	ARQ-010	\N	\N
9	Lab Física	LAB-F01	\N	\N
\.


--
-- TOC entry 4912 (class 0 OID 27622)
-- Dependencies: 222
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id, created_at, last_modified_date, name) FROM stdin;
1	2025-04-07 11:39:06.0032	2025-04-07 11:39:06.0032	Profesor
2	2025-04-07 11:39:06.045266	2025-04-07 11:39:06.045266	Admin
\.


--
-- TOC entry 4914 (class 0 OID 27628)
-- Dependencies: 224
-- Data for Name: solicitud; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitud (id, cant_grupos, estado, fecha_solicitud, fecha_uso, horario, id_asignatura, id_laboratorio, id_usuario, created_at, last_modified_date, asignatura_id, laboratorio_id, usuario_id) FROM stdin;
5	3	f	2025-04-27	2025-04-28	15:33:00-03	3	6	12	\N	\N	\N	\N	\N
\.


--
-- TOC entry 4916 (class 0 OID 27634)
-- Dependencies: 226
-- Data for Name: solicitud_insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitud_insumo (id, cantidad, id_insumo, id_solicitud, created_at, last_modified_date, insumo_id, solicitud_id) FROM stdin;
7	1	2	5	\N	\N	\N	\N
8	3	3	5	\N	\N	\N	\N
9	2	4	5	\N	\N	\N	\N
\.


--
-- TOC entry 4918 (class 0 OID 27640)
-- Dependencies: 228
-- Data for Name: token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token (id, created_at, expires_at, status, token, validated_at, user_id, type) FROM stdin;
\.


--
-- TOC entry 4920 (class 0 OID 27647)
-- Dependencies: 230
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, account_locked, apellido, created_at, email, enabled, last_modified_date, nombre, password, reset_password_token) FROM stdin;
1	f	Istrador	2025-04-07 11:39:06.16028	admin	t	2025-04-07 11:39:06.16028	Admin	$2a$10$gvkGB49gKxphMD7NjnIFkucy2anIDTXyVuY2SliXSHQMkldpW9VTW	\N
2	f	Toro	2025-04-07 11:54:20.366143	brunotoro1799@gmail.com	t	2025-04-07 11:54:20.366143	Bruno	$2a$10$.22910oWcfTNGKXpym4L4e5kWrRSesgIjlaql3Iq99TR8tP.fh2O.	\N
12	f	Olmos	2025-04-26 15:11:25.562884	bruno.toro@alumnos.ucn.cl	t	2025-04-26 15:11:25.562884	Pedro	$2a$10$M5xgO0nZjt7Z406HhPQXr..k7KFAYuspRBmCr7xbcyDoPRrhjKZ3i	\N
\.


--
-- TOC entry 4921 (class 0 OID 27654)
-- Dependencies: 231
-- Data for Name: usuario_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_roles (users_id, roles_id) FROM stdin;
1	2
2	1
2	2
12	1
\.


--
-- TOC entry 4927 (class 0 OID 0)
-- Dependencies: 215
-- Name: asignatura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asignatura_id_seq', 11, true);


--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 217
-- Name: insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.insumo_id_seq', 8, true);


--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 219
-- Name: laboratorio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.laboratorio_id_seq', 9, true);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 221
-- Name: rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_seq', 2, true);


--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 223
-- Name: solicitud_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitud_id_seq', 5, true);


--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 225
-- Name: solicitud_insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitud_insumo_id_seq', 9, true);


--
-- TOC entry 4933 (class 0 OID 0)
-- Dependencies: 227
-- Name: token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_id_seq', 1, false);


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 229
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 12, true);


--
-- TOC entry 4730 (class 2606 OID 27606)
-- Name: asignatura asignatura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignatura
    ADD CONSTRAINT asignatura_pkey PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 27614)
-- Name: insumo insumo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.insumo
    ADD CONSTRAINT insumo_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2606 OID 27620)
-- Name: laboratorio laboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorio
    ADD CONSTRAINT laboratorio_pkey PRIMARY KEY (id);


--
-- TOC entry 4736 (class 2606 OID 27626)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);


--
-- TOC entry 4740 (class 2606 OID 27638)
-- Name: solicitud_insumo solicitud_insumo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud_insumo
    ADD CONSTRAINT solicitud_insumo_pkey PRIMARY KEY (id);


--
-- TOC entry 4738 (class 2606 OID 27632)
-- Name: solicitud solicitud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT solicitud_pkey PRIMARY KEY (id);


--
-- TOC entry 4742 (class 2606 OID 27645)
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- TOC entry 4744 (class 2606 OID 27660)
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- TOC entry 4746 (class 2606 OID 27653)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 27658)
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (users_id, roles_id);


--
-- TOC entry 4760 (class 2606 OID 27696)
-- Name: usuario_roles fk21t3sqh002xkps2g5l41m8nos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk21t3sqh002xkps2g5l41m8nos FOREIGN KEY (users_id) REFERENCES public.usuario(id);


--
-- TOC entry 4755 (class 2606 OID 27730)
-- Name: solicitud_insumo fk35ktf6m5760csyvqawn42r9pd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud_insumo
    ADD CONSTRAINT fk35ktf6m5760csyvqawn42r9pd FOREIGN KEY (solicitud_id) REFERENCES public.solicitud(id);


--
-- TOC entry 4759 (class 2606 OID 27686)
-- Name: token fk5kj7c5g7y3kfcrm7bx8e30qod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fk5kj7c5g7y3kfcrm7bx8e30qod FOREIGN KEY (user_id) REFERENCES public.usuario(id);


--
-- TOC entry 4749 (class 2606 OID 27666)
-- Name: solicitud fk65kcthnjf98kmdubxirq9myks; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fk65kcthnjf98kmdubxirq9myks FOREIGN KEY (id_laboratorio) REFERENCES public.laboratorio(id);


--
-- TOC entry 4750 (class 2606 OID 27720)
-- Name: solicitud fk6jl4i2eesvg305qkamgialwh3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fk6jl4i2eesvg305qkamgialwh3 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4751 (class 2606 OID 27661)
-- Name: solicitud fk6xa6w4nwoikkjvtq8hh5ud9kl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fk6xa6w4nwoikkjvtq8hh5ud9kl FOREIGN KEY (id_asignatura) REFERENCES public.asignatura(id);


--
-- TOC entry 4761 (class 2606 OID 27691)
-- Name: usuario_roles fk861wr18rjyh6pmadvor1u36vb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk861wr18rjyh6pmadvor1u36vb FOREIGN KEY (roles_id) REFERENCES public.rol(id);


--
-- TOC entry 4752 (class 2606 OID 27715)
-- Name: solicitud fk8d5tlyvrgld0j0yt75tp334lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fk8d5tlyvrgld0j0yt75tp334lo FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorio(id);


--
-- TOC entry 4753 (class 2606 OID 27710)
-- Name: solicitud fkfaxynuyipdi9jyhp80ffu2qpm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fkfaxynuyipdi9jyhp80ffu2qpm FOREIGN KEY (asignatura_id) REFERENCES public.asignatura(id);


--
-- TOC entry 4756 (class 2606 OID 27681)
-- Name: solicitud_insumo fkkfum8qktsid10qt862l78y3px; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud_insumo
    ADD CONSTRAINT fkkfum8qktsid10qt862l78y3px FOREIGN KEY (id_solicitud) REFERENCES public.solicitud(id);


--
-- TOC entry 4754 (class 2606 OID 27671)
-- Name: solicitud fknm4y7w49isl37c27aq2fmos5t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fknm4y7w49isl37c27aq2fmos5t FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- TOC entry 4757 (class 2606 OID 27676)
-- Name: solicitud_insumo fkpes6n1ab90qjjdqbv19nrlr5p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud_insumo
    ADD CONSTRAINT fkpes6n1ab90qjjdqbv19nrlr5p FOREIGN KEY (id_insumo) REFERENCES public.insumo(id);


--
-- TOC entry 4758 (class 2606 OID 27725)
-- Name: solicitud_insumo fkpjfi0ko0x0dmjc6kw9li0efe1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitud_insumo
    ADD CONSTRAINT fkpjfi0ko0x0dmjc6kw9li0efe1 FOREIGN KEY (insumo_id) REFERENCES public.insumo(id);


-- Completed on 2025-04-27 21:56:56

--
-- PostgreSQL database dump complete
--

